  
name: ðŸ¦–
on: [push, workflow_dispatch]
jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: normal-artifact
          path: my-artifact.txt
      - uses: actions/upload-artifact@v2
        with:
          name: custom-artifact
          path: my-artifact.txt
          retention-days: 7

